import Head from "next/head";
import { useCountryData } from "@/utils/useCountryDetails";
import CountryCard from "@/src/components/CountryCard";
import ErrorBoundary from "@/src/components/ErrorBoundary";
import FilterCountriesByRegion from "@/src/components/FilterCountriesByRegion";
import SearchCountryByName from "@/src/components/SearchCountryByName";
import SortByPopulation from "@/src/components/SortByPupulation";
import styles from "@/styles/Home.module.css";
import Loader from "@/src/components/Loader";



export default function Home() {
  const { filteredData, regions, isLoading, error, filters, updateFilters } = useCountryData();
  if (isLoading) return <Loader/>
  if (error) return <div>{error}</div>;


  return (
    <>
      <Head>
        <title>Countries Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
          <ErrorBoundary>
          <div className={styles.header}>
          <div className={styles.searchBar}>
            <FilterCountriesByRegion
              regions={regions}
              onFilter={(region) => updateFilters({ region })}
            />
            <SearchCountryByName
              searchTerm={filters.searchTerm}
              onSearch={(term) => updateFilters({ searchTerm: term })}
            />
            <SortByPopulation
              onSort={(order) => updateFilters({ sortOrder: order })}
            />
            </div>
            </div>
            <div className="grid">
              {filteredData.map((country) => (
                <CountryCard key={country.name.common} country={country} />
              ))}
            </div>
          </ErrorBoundary>
    </>
  );
}
